apisix:
  node_listen: 9080
  enable_ipv6: false

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml

plugin_attr:
  limit-count:
    redis:
      host: "redis"
      port: 6379
      database: 1
      timeout: 1000
      password: ""

  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

plugins:
  - real-ip
  - request-id
  - cors
  - jwt-auth
  - limit-count
  - elasticsearch-logger
  - prometheus
  - opentelemetry
  - proxy-rewrite
  - fault-injection
